defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

path:
  input: E:\Dataset\record\input
  temp: E:\Dataset\record\temp
  result: E:\Dataset\record\output
  video: E:\Dataset\record\input

headless: true

